services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER: ${USER}
        PHP_VERSION: ${PHP_VERSION:-8.2}
    environment:
      XDEBUG_CONFIG: "remote_host=hostdocker.internal"
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_HOST: mysql
      COMPOSER_HOME: /tmp
    extra_hosts:
      - "hostdocker.internal:host-gateway"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf


  nginx:
    image: nginx:1.23-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
