services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER: ${USER}
        PHP_VERSION: ${PHP_VERSION:-8.2}
    environment:
      XDEBUG_CONFIG: "remote_host=hostdocker.internal"
    extra_hosts:
      - "hostdocker.internal:host-gateway"
    # depends_on:
    #   - postgres
    volumes:
      - .:/var/www/
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf


  nginx:
    image: nginx:1.23-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  # postgres:
  #   build:
  #     dockerfile: docker/postgres/Dockerfile
  #     context: .
  #   volumes:
  #     - docker/postgres/postgres.conf:/etc/postgresql/postgresql.conf
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=docker
  #     - POSTGRES_USER=docker
  #     - POSTGRES_DB=docker
  #   command: postgres -c config_file=/etc/postgresql/postgresql.conf
